"""empty message

Revision ID: 64908de96bba
Revises: 
Create Date: 2018-02-04 23:13:42.269602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64908de96bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
